name: self_reliance_analytics
version: "1.0.0"
config-version: 2
profile: self_reliance_analytics

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  self_reliance_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
