#!/usr/bin/env bash
# Creates the production .env once, with generated passwords. Run as root.
# Never committed; `deploy.sh` refuses to run without it.
set -euo pipefail

APP_DIR=${APP_DIR:-/var/www/production/self-reliance-analytics-platform}
ENV_FILE="$APP_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists — leaving it alone."
  exit 0
fi

gen() { openssl rand -base64 24 | tr -d '/+=' | head -c 28; }

umask 077
cat > "$ENV_FILE" <<VARS
# Generated by deploy/init-env.sh — production only, never commit.
POSTGRES_DB=self_reliance
POSTGRES_USER=sr_app
POSTGRES_PASSWORD=$(gen)

CLICKHOUSE_DB=self_reliance
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=$(gen)

CLIENTS_API_DB_NAME=self_reliance_ops
CLIENTS_API_DB_USER=sr_app
CLIENTS_API_DB_PASSWORD=$(gen)
CLIENTS_API_KEY=$(gen)

AIRFLOW_ADMIN_USER=admin
AIRFLOW_ADMIN_PASSWORD=$(gen)

GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$(gen)

APP_DOMAIN=example.com
VARS

chown deploy:app-admins "$ENV_FILE"
chmod 640 "$ENV_FILE"
echo "wrote $ENV_FILE (0640 deploy:app-admins)"
echo "Admin logins:"
grep -E '^(AIRFLOW_ADMIN|GRAFANA_ADMIN)' "$ENV_FILE"
