/** Regions a client's names are drawn from, following their origin community. */
export enum NameRegion {
  GREAT_LAKES = 'GREAT_LAKES',
  HORN_OF_AFRICA = 'HORN_OF_AFRICA',
  NILE_VALLEY = 'NILE_VALLEY',
  SAHEL = 'SAHEL',
}

export interface NamePool {
  female: string[];
  male: string[];
  family: string[];
}

/**
 * Given and family names by region, so generated people read as plausible for
 * where they actually live rather than as generic faker output. Pure data —
 * the region lookup that selects between them lives in name-regions.ts.
 */
export const NAME_POOLS: Record<NameRegion, NamePool> = {
  [NameRegion.GREAT_LAKES]: {
    female: [
      'Uwase',
      'Mukamana',
      'Nyirahabimana',
      'Ingabire',
      'Umutoni',
      'Furaha',
      'Neema',
      'Chantal',
      'Esperance',
      'Jeanne',
      'Clarisse',
      'Mapendo',
      'Riziki',
      'Sifa',
      'Anuarite',
      'Kavira',
    ],
    male: [
      'Habimana',
      'Niyonzima',
      'Bizimana',
      'Ndayisaba',
      'Hakizimana',
      'Emmanuel',
      'Jean Bosco',
      'Innocent',
      'Fiston',
      'Mwenda',
      'Kambale',
      'Baraka',
      'Amani',
      'Patrick',
      'Olivier',
      'Chirac',
    ],
    family: [
      'Mugisha',
      'Uwimana',
      'Nsengiyumva',
      'Ntakirutimana',
      'Bagaza',
      'Kabera',
      'Mbonyi',
      'Rukundo',
      'Byiringiro',
      'Kanyange',
      'Lukusa',
      'Mulumba',
      'Kasongo',
      'Bahati',
      'Muhindo',
      'Nzeyimana',
    ],
  },
  [NameRegion.HORN_OF_AFRICA]: {
    female: [
      'Amina',
      'Halima',
      'Fardowsa',
      'Ubah',
      'Sagal',
      'Deqa',
      'Ifrah',
      'Hodan',
      'Meseret',
      'Tigist',
      'Bethlehem',
      'Selamawit',
      'Hiwot',
      'Almaz',
      'Chaltu',
      'Zeinab',
    ],
    male: [
      'Abdirahman',
      'Hassan',
      'Mohamed',
      'Ahmed',
      'Yusuf',
      'Abdi',
      'Omar',
      'Ibrahim',
      'Getachew',
      'Tesfaye',
      'Dawit',
      'Bekele',
      'Girma',
      'Solomon',
      'Kedir',
      'Jamal',
    ],
    family: [
      'Farah',
      'Warsame',
      'Adan',
      'Noor',
      'Hersi',
      'Gedi',
      'Osman',
      'Kassa',
      'Wolde',
      'Abebe',
      'Mengistu',
      'Desta',
      'Gebremariam',
      'Aden',
      'Diriye',
      'Elmi',
    ],
  },
  [NameRegion.NILE_VALLEY]: {
    female: [
      'Nyandeng',
      'Achol',
      'Nyakuoth',
      'Aluel',
      'Adut',
      'Nyibol',
      'Awut',
      'Rebecca',
      'Sarah',
      'Mary',
      'Nyalong',
      'Amel',
      'Zeinab',
      'Fatima',
      'Nyaruot',
      'Abuk',
    ],
    male: [
      'Deng',
      'Majok',
      'Gatluak',
      'Chol',
      'Lual',
      'Riek',
      'Puok',
      'Simon',
      'Peter',
      'James',
      'Malual',
      'Kuol',
      'Bol',
      'Osman',
      'Abdelrahman',
      'Yien',
    ],
    family: [
      'Deng',
      'Majok',
      'Garang',
      'Nyuon',
      'Chuol',
      'Gatkuoth',
      'Wol',
      'Ajak',
      'Ngor',
      'Malok',
      'Ibrahim',
      'Hassan',
      'Adam',
      'Yahya',
      'Bakhit',
      'Tut',
    ],
  },
  [NameRegion.SAHEL]: {
    female: [
      'Fatime',
      'Achta',
      'Halime',
      'Mariam',
      'Zara',
      'Hadje',
      'Amina',
      'Khadidja',
      'Aissatou',
      'Ndeye',
      'Roukaya',
      'Safia',
      'Nadjet',
      'Hawa',
      'Bintou',
      'Djamila',
    ],
    male: [
      'Mahamat',
      'Abdoulaye',
      'Idriss',
      'Ousmane',
      'Brahim',
      'Adoum',
      'Djibrine',
      'Youssouf',
      'Hissein',
      'Souleymane',
      'Moussa',
      'Ali',
      'Saleh',
      'Abakar',
      'Nour',
      'Zakaria',
    ],
    family: [
      'Mahamat',
      'Abakar',
      'Hassane',
      'Djibrine',
      'Ousman',
      'Ngarta',
      'Deby',
      'Adoum',
      'Nour',
      'Saleh',
      'Toure',
      'Diallo',
      'Barka',
      'Yacoub',
      'Ramadan',
      'Zene',
    ],
  },
};
