import { Gender } from '../clients.constants';

/**
 * Name pools grouped by the region a client (or their origin community) comes
 * from, so generated people read as plausible for where they actually live
 * rather than as generic faker output.
 */
export enum NameRegion {
  GREAT_LAKES = 'GREAT_LAKES',
  HORN_OF_AFRICA = 'HORN_OF_AFRICA',
  NILE_VALLEY = 'NILE_VALLEY',
  SAHEL = 'SAHEL',
}

export interface NamePool {
  female: string[];
  male: string[];
  family: string[];
}

export const NAME_POOLS: Record<NameRegion, NamePool> = {
  [NameRegion.GREAT_LAKES]: {
    female: [
      'Uwase',
      'Mukamana',
      'Nyirahabimana',
      'Ingabire',
      'Umutoni',
      'Furaha',
      'Neema',
      'Chantal',
      'Esperance',
      'Jeanne',
      'Clarisse',
      'Mapendo',
      'Riziki',
      'Sifa',
      'Anuarite',
      'Kavira',
    ],
    male: [
      'Habimana',
      'Niyonzima',
      'Bizimana',
      'Ndayisaba',
      'Hakizimana',
      'Emmanuel',
      'Jean Bosco',
      'Innocent',
      'Fiston',
      'Mwenda',
      'Kambale',
      'Baraka',
      'Amani',
      'Patrick',
      'Olivier',
      'Chirac',
    ],
    family: [
      'Mugisha',
      'Uwimana',
      'Nsengiyumva',
      'Ntakirutimana',
      'Bagaza',
      'Kabera',
      'Mbonyi',
      'Rukundo',
      'Byiringiro',
      'Kanyange',
      'Lukusa',
      'Mulumba',
      'Kasongo',
      'Bahati',
      'Muhindo',
      'Nzeyimana',
    ],
  },
  [NameRegion.HORN_OF_AFRICA]: {
    female: [
      'Amina',
      'Halima',
      'Fardowsa',
      'Ubah',
      'Sagal',
      'Deqa',
      'Ifrah',
      'Hodan',
      'Meseret',
      'Tigist',
      'Bethlehem',
      'Selamawit',
      'Hiwot',
      'Almaz',
      'Chaltu',
      'Zeinab',
    ],
    male: [
      'Abdirahman',
      'Hassan',
      'Mohamed',
      'Ahmed',
      'Yusuf',
      'Abdi',
      'Omar',
      'Ibrahim',
      'Getachew',
      'Tesfaye',
      'Dawit',
      'Bekele',
      'Girma',
      'Solomon',
      'Kedir',
      'Jamal',
    ],
    family: [
      'Farah',
      'Warsame',
      'Adan',
      'Noor',
      'Hersi',
      'Gedi',
      'Osman',
      'Kassa',
      'Wolde',
      'Abebe',
      'Mengistu',
      'Desta',
      'Gebremariam',
      'Aden',
      'Diriye',
      'Elmi',
    ],
  },
  [NameRegion.NILE_VALLEY]: {
    female: [
      'Nyandeng',
      'Achol',
      'Nyakuoth',
      'Aluel',
      'Adut',
      'Nyibol',
      'Awut',
      'Rebecca',
      'Sarah',
      'Mary',
      'Nyalong',
      'Amel',
      'Zeinab',
      'Fatima',
      'Nyaruot',
      'Abuk',
    ],
    male: [
      'Deng',
      'Majok',
      'Gatluak',
      'Chol',
      'Lual',
      'Riek',
      'Puok',
      'Simon',
      'Peter',
      'James',
      'Malual',
      'Kuol',
      'Bol',
      'Osman',
      'Abdelrahman',
      'Yien',
    ],
    family: [
      'Deng',
      'Majok',
      'Garang',
      'Nyuon',
      'Chuol',
      'Gatkuoth',
      'Wol',
      'Ajak',
      'Ngor',
      'Malok',
      'Ibrahim',
      'Hassan',
      'Adam',
      'Yahya',
      'Bakhit',
      'Tut',
    ],
  },
  [NameRegion.SAHEL]: {
    female: [
      'Fatime',
      'Achta',
      'Halime',
      'Mariam',
      'Zara',
      'Hadje',
      'Amina',
      'Khadidja',
      'Aissatou',
      'Ndeye',
      'Roukaya',
      'Safia',
      'Nadjet',
      'Hawa',
      'Bintou',
      'Djamila',
    ],
    male: [
      'Mahamat',
      'Abdoulaye',
      'Idriss',
      'Ousmane',
      'Brahim',
      'Adoum',
      'Djibrine',
      'Youssouf',
      'Hissein',
      'Souleymane',
      'Moussa',
      'Ali',
      'Saleh',
      'Abakar',
      'Nour',
      'Zakaria',
    ],
    family: [
      'Mahamat',
      'Abakar',
      'Hassane',
      'Djibrine',
      'Ousman',
      'Ngarta',
      'Deby',
      'Adoum',
      'Nour',
      'Saleh',
      'Toure',
      'Diallo',
      'Barka',
      'Yacoub',
      'Ramadan',
      'Zene',
    ],
  },
};

/** Origin (or host) country ISO3 -> naming region. */
const REGION_BY_ISO3: Record<string, NameRegion> = {
  RWA: NameRegion.GREAT_LAKES,
  BDI: NameRegion.GREAT_LAKES,
  COD: NameRegion.GREAT_LAKES,
  KEN: NameRegion.HORN_OF_AFRICA,
  ETH: NameRegion.HORN_OF_AFRICA,
  SOM: NameRegion.HORN_OF_AFRICA,
  ERI: NameRegion.HORN_OF_AFRICA,
  SSD: NameRegion.NILE_VALLEY,
  SDN: NameRegion.NILE_VALLEY,
  TCD: NameRegion.SAHEL,
  CAF: NameRegion.SAHEL,
  NGA: NameRegion.SAHEL,
  CMR: NameRegion.SAHEL,
};

export function resolveNameRegion(iso3: string): NameRegion {
  return REGION_BY_ISO3[iso3.toUpperCase()] ?? NameRegion.GREAT_LAKES;
}

export function getGivenNamePool(region: NameRegion, gender: Gender): string[] {
  const pool = NAME_POOLS[region];
  return gender === Gender.FEMALE ? pool.female : pool.male;
}

export function getFamilyNamePool(region: NameRegion): string[] {
  return NAME_POOLS[region].family;
}

/** Business advisors are program staff, drawn from the host country. */
export const ADVISORY_TOPICS = [
  'Record keeping basics',
  'Pricing and margins',
  'Customer acquisition',
  'Inventory management',
  'Savings discipline',
  'Loan readiness and repayment planning',
  'Digital payments onboarding',
  'Supplier negotiation',
  'Business formalisation',
  'Cash flow forecasting',
  'Market linkage to host traders',
  'Product quality and packaging',
];
